// AQUI ACONTECE O HOISTING QUE O JAVASCRIPT FAZ E PROCURAR A VAR PARA AI SIM CONSEGUIR LANÇAR O A INFORMAÇÃO SE NÃO
// ELE VAI LANÇAR O VALOR COMO INDEFINIDO 
console.log('a =', a)
var a = 2
console.log('a =', a)