console.log('01)', '1' == 1) // COMPARANDO O VALOR E NÃO O TIPO
console.log('02)', '1' === 1) // ESTÁ COMPARANDO ESTRITAMENTE OS VALORES E O TIPO
console.log('03)', '3' != 3) // ESTÁ VERIFICANDO SE UM NUMERO E DIFERENTE DO OUTRO, E ESTÁ COMPARANDO O VALOR NÃO O TIPO
console.log('04)', '3' !== 3) // ESTRITAMENTE DIFERENTE COMPARANDO O O VALOR E O TIPO

console.log('05)', 3 < 2) // COMPARANDO SE O 3 E MENOR QUE 2
console.log('06)', 3 > 2) // COMPARANDO SE O 3 É MAIOR QUE 2
console.log('07)', 3 <= 2) // COMPARANDO SE 3 É MENOR OU IGUAL A 2
console.log('08)', 3 >= 2) // COMPARANDO SE 3 É MAIOR OU IGUAL A 2

const d1 = new Date(0) // new Date -- É PARA DATA E QUANDO TEM 0 ELE TRAS A PRIMEIRA DATA EXISTENTE NO JAVASCRIPT
const d2 = new Date(0)
console.log('09)', d1 === d2) // COMPARANDO SE OS TIPOS SÃO ESTRITAMENTE IGUASI, PORÉM NÃO ESTÃO 
// VERIFICANDO A DATA E SIM O LOCAL QUE NO CASO É D1 E D2
console.log('10)', d1 == d2) // COMPARANDO APENAS O VALOR
console.log('11)', d1.getTime() == d2.getTime()) // COMPARANDO O VALOR E O TIPO DENTRO DE NEW DATE QUE SÃO OS MESMOS
 